services:
  django:
    build: .
    command: ["sh", "-c", "python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5679 manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5679:5679"
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine3.19
    ports:
      - "5432:5432"
    env_file:
      - .env
