services:
  django:
    build: .
    command: ["sh", "-c", "python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5679 manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5679:5679"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:alpine3.19
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - "6379:6379"
    env_file:
      - .env

volumes:
  dbdata: null
