# Generated by Django 5.0.3 on 2024-03-29 21:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("country", models.CharField(max_length=150, verbose_name="country")),
                ("zip_code", models.CharField(max_length=150, verbose_name="zip_code")),
                ("state", models.CharField(max_length=150, verbose_name="state")),
                ("street", models.CharField(max_length=150, verbose_name="street")),
                ("number", models.CharField(max_length=150, verbose_name="number")),
                (
                    "complement",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="complement"
                    ),
                ),
                (
                    "is_main_delivery",
                    models.BooleanField(
                        default=False, verbose_name="main delivery address"
                    ),
                ),
                (
                    "is_main_billing",
                    models.BooleanField(
                        default=False, verbose_name="main billing address"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
