# Generated by Django 5.0.3 on 2024-03-29 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_profile_created_at_profile_updated_at_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.profile"
            ),
        ),
    ]
