# Generated by Django 5.0.3 on 2024-03-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="product name")),
                (
                    "brand",
                    models.CharField(max_length=100, verbose_name="product brand"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="product price"
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        to="api.subcategory", verbose_name="categories"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
