# Generated by Django 5.0.3 on 2024-03-31 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_orderproducts_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="order",
            name="consumption",
            field=models.CharField(
                choices=[
                    ("TAKE HOME", "Take home"),
                    ("EAT IN", "Eat in"),
                    ("DELIVERY", "Delivery"),
                ],
                default="EAT IN",
                max_length=50,
                verbose_name="consumption option",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CANCELED", "Canceled"),
                    ("ON QUEUE", "On queue"),
                    ("PREPARING", "Preparing"),
                    ("READY", "Ready"),
                ],
                default="PREPARING",
                max_length=20,
                verbose_name="order status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user id",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("number", "created_at")},
        ),
    ]
