# Generated by Django 5.0.3 on 2024-04-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_order_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "order",
                "verbose_name_plural": "orders",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "verbose_name": "sub category",
                "verbose_name_plural": "sub categories",
            },
        ),
        migrations.RenameField(
            model_name="subcategory",
            old_name="category_id",
            new_name="category",
        ),
    ]
