# Generated by Django 5.0.4 on 2024-04-24 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_product_is_active"),
        ("sessions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="sessions.session",
                verbose_name="session key",
            ),
        ),
    ]
