# Generated by Django 5.0.4 on 2024-05-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_order_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="session",
            field=models.CharField(
                max_length=40, null=True, verbose_name="session key"
            ),
        ),
    ]
